### ISSUE TITLE
Exception: Gaaa!

### ISSUE THREAD

**Issue by mgedmin** [collective/collective.xmltestreport#13]
https://pypi.python.org/packages/source/c/collective.xmltestreport/collective.xmltestreport-1.3.1.zip contains a file not present in the [source repository](https://github.com/collective/collective.xmltestreport/tree/1.3.1/collective/xmltestreport): collective/xmltestreport/tests/test_teardown.py, with the following contents:

```python
from unittest import TestCase


class Layer(object):

	__name__ = 'Layer'
	__bases__ = ()

	def setUp(self):
		pass

	def tearDown(self):
		raise Exception('Gaaa!')


class TestTearDown(TestCase):

	layer = Layer()

	def testFoo(self):
		pass
```

This "test file" gets included in my test suite for silly reasons having to do with buildout and zc.recipe.testrunner, and causes a failure when I forget to filter it out.

**Comment by mauritsvanrees** [comment]
I have just released 1.3.2, which does not have this file.
