### ISSUE TITLE
environment option broken

### ISSUE THREAD

**Issue by icemac** [collective/collective.xmltestreport#8]
Since version 1.2.8 (fix of issue #5) the `environment` option is broken in the same way as it is broken in `zc.recipe.testrunner`: The contents of the `environment` option are not rendered in the generated script when using a virtualenv Python.

Example: See the following `buildout.cfg`:

```config
[buildout]
parts = test
versions = versions

[versions]
collective.xmltestreport = 1.2.6

[test-env]
foo = bar

[test]
recipe = collective.xmltestreport
eggs = collective.xmltestreport
environment = test-env
```

When used with a Python interpreter from a virtualenv it renders `bin/test` like this:

```python
#!/opt/2.7/bin/python

import sys
sys.path[0:0] = [...]

import os
...
os.environ['foo'] = 'bar'


import collective.xmltestreport.runner

if __name__ == '__main__':
    ...
```

After upgrading to 1.2.8 the block beginning with `import os`  is missing.

**Comment by mauritsvanrees** [comment]
Since that pull request was closed because it was no longer needed, I guess this issue can be closed too.  Please reopen if this is still an issue.
